# Generated by Django 5.2.7 on 2025-10-26 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_latitude', models.FloatField(blank=True, null=True)),
                ('starting_longitude', models.FloatField(blank=True, null=True)),
                ('final_latitude', models.FloatField(blank=True, null=True)),
                ('final_longitude', models.FloatField(blank=True, null=True)),
                ('starting_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('final_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
                ('attendance_list', models.ManyToManyField(related_name='attendance_list', to=settings.AUTH_USER_MODEL)),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
