# Generated by Django 5.2.7 on 2025-10-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_latitude', models.FloatField(blank=True, null=True)),
                ('starting_longitude', models.FloatField(blank=True, null=True)),
                ('final_latitude', models.FloatField(blank=True, null=True)),
                ('final_longitude', models.FloatField(blank=True, null=True)),
                ('starting_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('final_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
