# Generated by Django 5.2.7 on 2025-10-26 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_remove_route_attendance_list_attendancelist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='attendance_list',
            field=models.ManyToManyField(blank=True, related_name='attendance_list', through='map.AttendanceList', to=settings.AUTH_USER_MODEL),
        ),
    ]
