# Generated by Django 5.2.7 on 2025-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, null=True)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
